package nexusglobal.wordprocessor.enums;

public enum EmailTemplatePlaceholder {
    ACCOUNT_COMPANY_NAME,
    ACCOUNT_MANAGER,
    ACCOUNT_SCHEMA,
    ACCOUNT_FIRSTNAME,
    ACCOUNT_LASTNAME,
    ACCOUNT_EMAIL,
    ACCOUNT_PLANS,
    SUPPORT_EMAIL,
    APMSUITE_BASE_URL,
    APMSUITE_RESETPASSWORD_URL,
    APMSUITE_RESETPASSWORD_UUID,
    EXPIRY_DATE,
    STACK_TRACE,
}
